continentes  = {
    'Afghanistan': 'Ásia',
    'Albania': 'Europa',
    'Algeria': 'África',
    'Andorra': 'Europa',
    'Angola': 'África',
    'Antigua and Barbuda': 'América do Norte',
    'Argentina': 'América do Sul',
    'Armenia': 'Europa',
    'Australia': 'Oceania',
    'Austria': 'Europa',
    'Azerbaijan': 'Europa',
    'Bahamas': 'América do Norte',
    'Bahrain': 'Ásia',
    'Bangladesh': 'Ásia',
    'Barbados': 'América do Norte',
    'Belarus': 'Europa',
    'Belgium': 'Europa',
    'Belize': 'América Central',
    'Benin': 'África',
    'Bhutan': 'Ásia',
    'Bolivia': 'América do Sul',
    'Bosnia and Herzegovina': 'Europa',
    'Botswana': 'África',
    'Brazil': 'América do Sul',
    'Brunei': 'Ásia',
    'Bulgaria': 'Europa',
    'Burkina Faso': 'África',
    'Burundi': 'África',
    'Cabo Verde': 'África',
    'Cambodia': 'Ásia',
    'Cameroon': 'África',
    'Canada': 'América do Norte',
    'Central African Republic': 'África',
    'Chad': 'África',
    'Chile': 'América do Sul',
    'China': 'Ásia',
    'Colombia': 'América do Sul',
    'Comoros': 'África',
    'Congo, Dem. Rep.': 'África',
    'Congo, Rep.': 'África',
    'Costa Rica': 'América Central',
    "Cote d'Ivoire": 'África',
    'Croatia': 'Europa',
    'Cuba': 'América do Norte',
    'Cyprus': 'Europa',
    'Czech Republic': 'Europa',
    'Denmark': 'Europa',
    'Djibouti': 'África',
    'Dominica': 'América do Norte',
    'Dominican Republic': 'América do Norte',
    'Ecuador': 'América do Sul',
    'Egypt': 'África',
    'El Salvador': 'América Central',
    'Equatorial Guinea': 'África',
    'Eritrea': 'África',
    'Estonia': 'Europa',
    'Eswatini': 'África',
    'Ethiopia': 'África',
    'Fiji': 'Oceania',
    'Finland': 'Europa',
    'France': 'Europa',
    'Gabon': 'África',
    'Gambia': 'África',
    'Georgia': 'Europa',
    'Germany': 'Europa',
    'Ghana': 'África',
    'Greece': 'Europa',
    'Grenada': 'América do Norte',
    'Guatemala': 'América Central',
    'Guinea': 'África',
    'Guinea-Bissau': 'África',
    'Guyana': 'América do Sul',
    'Haiti': 'América do Norte',
    'Honduras': 'América Central',
    'Hungary': 'Europa',
    'Iceland': 'Europa',
    'India': 'Ásia',
    'Indonesia': 'Ásia',
    'Iran': 'Ásia',
    'Iraq': 'Ásia',
    'Ireland': 'Europa',
    'Israel': 'Ásia',
    'Italy': 'Europa',
    'Jamaica': 'América do Norte',
    'Japan': 'Ásia',
    'Jordan': 'Ásia',
    'Kazakhstan': 'Ásia',
    'Kenya': 'África',
    'Kiribati': 'Oceania',
    'Korea, Dem. Rep.': 'Ásia',
    'Korea, Rep.': 'Ásia',
    'Kosovo': 'Europa',
    'Kuwait': 'Ásia',
    'Kyrgyz Republic': 'Ásia',
    'Lao': 'Ásia',
    'Latvia': 'Europa',
    'Lebanon': 'Ásia',
    'Lesotho': 'África',
    'Liberia': 'África',
    'Libya': 'África',
    'Liechtenstein': 'Europa',
    'Lithuania': 'Europa',
    'Luxembourg': 'Europa',
    'Madagascar': 'África',
    'Malawi': 'África',
    'Malaysia': 'Ásia',
    'Maldives': 'Ásia',
    'Mali': 'África',
    'Malta': 'Europa',
    'Marshall Islands': 'Oceania',
    'Mauritania': 'África',
    'Mauritius': 'África',
    'Mexico': 'América do Norte',
    'Micronesia, Fed. Sts.': 'Oceania',
    'Moldova': 'Europa',
    'Monaco': 'Europa',
    'Mongolia': 'Ásia',
    'Montenegro': 'Europa',
    'Morocco': 'África',
    'Mozambique': 'África',
    'Myanmar': 'Ásia',
    'Namibia': 'África',
    'Nauru': 'Oceania',
    'Nepal': 'Ásia',
    'Netherlands': 'Europa',
    'New Zealand': 'Oceania',
    'Nicaragua': 'América Central',
    'Niger': 'África',
    'Nigeria': 'África',
    'North Macedonia': 'Europa',
    'Norway': 'Europa',
    'Oman': 'Ásia',
    'Pakistan': 'Ásia',
    'Palau': 'Oceania',
    'Panama': 'América Central',
    'Papua New Guinea': 'Oceania',
    'Paraguay': 'América do Sul',
    'Peru': 'América do Sul',
    'Philippines': 'Ásia',
    'Poland': 'Europa',
    'Portugal': 'Europa',
    'Qatar': 'Ásia',
    'Romania': 'Europa',
    'Russia': 'Europa',
    'Rwanda': 'África',
    'Samoa': 'Oceania',
    'San Marino': 'Europa',
    'Sao Tome and Principe': 'África',
    'Saudi Arabia': 'Ásia',
    'Senegal': 'África',
    'Serbia': 'Europa',
    'Seychelles': 'África',
    'Sierra Leone': 'África',
    'Singapore': 'Ásia',
    'Slovak Republic': 'Europa',
    'Slovenia': 'Europa',
    'Solomon Islands': 'Oceania',
    'Somalia': 'África',
    'South Africa': 'África',
    'South Sudan': 'África',
    'Spain': 'Europa',
    'Sri Lanka': 'Ásia',
    'Sudan': 'África',
    'Suriname': 'América do Sul',
    'Sweden': 'Europa',
    'Switzerland': 'Europa',
    'Syria': 'Ásia',
    'Tajikistan': 'Ásia',
    'Tanzania': 'África',
    'Thailand': 'Ásia',
    'Timor-Leste': 'Ásia',
    'Togo': 'África',
    'Tonga': 'Oceania',
    'Trinidad and Tobago': 'América do Norte',
    'Tunisia': 'África',
    'Turkey': 'Ásia',
    'Turkmenistan': 'Ásia',
    'Tuvalu': 'Oceania',
    'Uganda': 'África',
    'Ukraine': 'Europa',
    'United Arab Emirates': 'Ásia',
    'United Kingdom': 'Europa',
    'United States': 'América do Norte',
    'Uruguay': 'América do Sul',
    'Uzbekistan': 'Ásia',
    'Vanuatu': 'Oceania',
    'Vatican City': 'Europa',
    'Venezuela': 'América do Sul',
    'Vietnam': 'Ásia',
    'Yemen': 'Ásia',
    'Zambia': 'África',
    'Zimbabwe': 'África'
}